[package]
name = "globject-rs"
version = "0.0.1"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
glcore-rs = "0.1.5"
half = "2.6.0"
nalgebra-glm = "0.19.0"
struct_iterable = "0.1.1"
zerocopy = { version = "0.8.26", features = ["derive"] }

[dev-dependencies]
glfw = "0.59.0"
